name: python-315

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "12 * * * *"

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      version: "3.15"
      tx_project: "python-newest"
    secrets: inherit
    